using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NiteAdvServerCore.Managers
{
    public class SetValueAttribute : Attribute
    {
        public string GetString
        {
            get
            {
                return "user";
            }
        }
        public DateTime GetDate
        {
            get
            {
                return DateTime.UtcNow;
            }
        }

        public byte[] GetBytes
        {
            get
            {
                return Guid.NewGuid().ToByteArray();
            }
        }

        public int GetInt(int? oldValue)
        {
            if (oldValue == null)
                return 1;
            else
                return oldValue.Value + 1;
        }

    }

    public class SetValueIfNullAttribute : Attribute
    {
        public string GetString
        {
            get
            {
                return "user";
            }
        }
        public DateTime GetDate
        {
            get
            {
                return DateTime.UtcNow;
            }
        }

        public byte[] GetBytes
        {
            get
            {
                return Guid.NewGuid().ToByteArray();
            }
        }

    }

    public class IgnoreAttribute:Attribute
    {

    }

    public class PrimaryKeyAttribute : Attribute
    {
        public PrimaryKeyAttribute(PrimaryKeyType _typePk)
        {
         TypePk= _typePk;
        }
        public PrimaryKeyType TypePk { get; set; }
    }
    public enum PrimaryKeyType
    {
        Autogenerated,
        Calculated
    }

    public class TableNameAttribute : Attribute
    {
        public TableNameAttribute(String _tablename)
        {
            TableName = _tablename;
        }
        public String TableName { get; set; }
    }
}










     

