CREATE TABLE [dbo].[City]
(
    [Id] INT NOT NULL PRIMARY KEY,
	[Description] [nvarchar](200) NOT NULL,
	[Deep] [int] NOT NULL Default(0),
	[Longitude] DECIMAL(12,9)  NULL,
	[Latitude]  DECIMAL(12,9)  NULL,
	[State] [nvarchar](100)  NULL,
	[LastSyncDate] [DateTime] NOT NULL Default GETDATE(),
)
CREATE TABLE [dbo].[StatusDescription]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Description] [nvarchar](200) NOT NULL,
)
CREATE TABLE [dbo].[Config]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[DockerId] [nvarchar](500) NOT NULL,
	[Port] [nvarchar](6) NOT NULL,
    [MongooseUrl] [nvarchar](600) NOT NULL,
	[TickMinutes] [int] NOT NULL Default(0),
)
CREATE TABLE [dbo].[Status]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[IdConfig] INT NOT NULL ,
	[IdStatusDescription] INT NOT NULL,
    [DeviceIp] [nvarchar](200) NOT NULL,
	[Message] [nvarchar](Max)  NULL,
	[City] [nvarchar](200) NULL,
	[LastSyncDate] [DateTime] NOT NULL,
	CONSTRAINT [FK_Status_ToConfig] FOREIGN KEY ([IdConfig]) REFERENCES [dbo].[Config] ([Id]),
	CONSTRAINT [FK_Status_ToStatusDescription] FOREIGN KEY ([IdStatusDescription]) REFERENCES [dbo].[StatusDescription] ([Id]),
)

INSERT [dbo].[StatusDescription] ([Id],[Description]) VALUES (1,'Alive')
INSERT [dbo].[StatusDescription] ([Id],[Description]) VALUES (2,'Queued')
INSERT [dbo].[StatusDescription] ([Id],[Description]) VALUES (3,'Busy')
INSERT [dbo].[StatusDescription] ([Id],[Description]) VALUES (4,'Error')
CREATE TABLE [dbo].[Log]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Data]  [DateTime] NOT NULL,
	[DockerID] [nvarchar](100) NOT NULL,
	[Message]  [nvarchar](500) NOT NULL,
	[LogType]  [nvarchar](20) NOT NULL,
	[LastSyncDate] [DateTime]  NULL,
    CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED ([Id] ASC),
)
CREATE TABLE [dbo].[Nation]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Description] [nvarchar](200) NOT NULL
)

IF NOT EXISTS (SELECT * FROM [dbo].[Nation] WHERE [Id] = '1') BEGIN
INSERT INTO Nation ([Id], [Description]) VALUES
(1, 'Afghanistan'),
(2, 'Albania'),
(3, 'Algeria'),
(4, 'Andorra'),
(5, 'Angola'),
(6, 'Anguilla'),
(7, 'Antartide'),
(8, 'Antigua e Barbuda'),
(9, 'Arabia Saudita'),
(10, 'Argentina'),
(11, 'Armenia'),
(12, 'Aruba'),
(13, 'Australia'),
(14, 'Austria'),
(15, 'Azerbaigian'),
(16, 'Bahamas'),
(17, 'Bahrein'),
(18, 'Bangladesh'),
(19, 'Barbados'),
(20, 'Belgio'),
(21, 'Belize'),
(22, 'Benin'),
(23, 'Bermuda'),
(24, 'Bhutan'),
(25, 'Bielorussia'),
(26, 'Birmania'),
(27, 'Bolivia'),
(28, 'Bosnia ed Erzegovina'),
(29, 'Botswana'),
(30, 'Brasile'),
(31, 'Brunei'),
(32, 'Bulgaria'),
(33, 'Burkina Faso'),
(34, 'Burundi'),
(35, 'Cambogia'),
(36, 'Camerun'),
(37, 'Canada'),
(38, 'Capo Verde'),
(39, 'Ciad'),
(40, 'Cile'),
(41, 'Cina'),
(42, 'Cipro'),
(43, 'Citt'),
(44, 'Colombia'),
(45, 'Comore'),
(46, 'Corea del Nord'),
(47, 'Corea del Sud'),
(48, 'Costa d''Avorio'),
(49, 'Costa Rica'),
(50, 'Croazia'),
(51, 'Cuba'),
(52, 'Cura'),
(53, 'Danimarca'),
(54, 'Dominica'),
(55, 'Ecuador'),
(56, 'Egitto'),
(57, 'El Salvador'),
(58, 'Emirati Arabi Uniti'),
(59, 'Eritrea'),
(60, 'Estonia'),
(61, 'Etiopia'),
(62, 'Figi'),
(63, 'Filippine'),
(64, 'Finlandia'),
(65, 'Francia'),
(66, 'Gabon'),
(67, 'Gambia'),
(68, 'Georgia'),
(69, 'Georgia del Sud e isole Sandwich meridionali'),
(70, 'Germania'),
(71, 'Ghana'),
(72, 'Giamaica'),
(73, 'Giappone'),
(74, 'Gibilterra'),
(75, 'Gibuti'),
(76, 'Giordania'),
(77, 'Grecia'),
(78, 'Grenada'),
(79, 'Groenlandia'),
(80, 'Guadalupa'),
(81, 'Guam'),
(82, 'Guatemala'),
(83, 'Guernsey'),
(84, 'Guinea'),
(85, 'Guinea-Bissau'),
(86, 'Guinea Equatoriale'),
(87, 'Guyana'),
(88, 'Guyana francese'),
(89, 'Haiti'),
(90, 'Honduras'),
(91, 'Hong Kong'),
(92, 'India'),
(93, 'Indonesia'),
(94, 'Iran'),
(95, 'Iraq'),
(96, 'Irlanda'),
(97, 'Islanda'),
(98, 'Isola Bouvet'),
(99, 'Isola di Man'),
(100, 'Isola di Natale'),
(101, 'Isola Norfolk'),
(102, 'Isole '),
(103, 'Isole BES'),
(104, 'Isole Cayman'),
(105, 'Isole Cocos (Keeling)'),
(106, 'Isole Cook'),
(108, 'Isole Falkland'),
(109, 'Isole Heard e McDonald'),
(110, 'Isole Marianne Settentrionali'),
(111, 'Isole Marshall'),
(112, 'Isole minori esterne degli Stati Uniti'),
(113, 'Isole Pitcairn'),
(114, 'Isole Salomone'),
(115, 'Isole Vergini britanniche'),
(116, 'Isole Vergini americane'),
(117, 'Israele'),
(118, 'Italia'),
(119, 'Jersey'),
(120, 'Kazakistan'),
(121, 'Kenya'),
(122, 'Kirghizistan'),
(123, 'Kiribati'),
(124, 'Kuwait'),
(125, 'Laos'),
(126, 'Lesotho'),
(127, 'Lettonia'),
(128, 'Libano'),
(129, 'Liberia'),
(130, 'Libia'),
(131, 'Liechtenstein'),
(132, 'Lituania'),
(133, 'Lussemburgo'),
(134, 'Macao'),
(135, 'Macedonia'),
(136, 'Madagascar'),
(137, 'Malawi'),
(138, 'Malesia'),
(139, 'Maldive'),
(140, 'Mali'),
(141, 'Malta'),
(142, 'Marocco'),
(143, 'Martinica'),
(144, 'Mauritania'),
(145, 'Mauritius'),
(146, 'Mayotte'),
(147, 'Messico'),
(148, 'Micronesia'),
(149, 'Moldavia'),
(150, 'Mongolia'),
(151, 'Montenegro'),
(152, 'Montserrat'),
(153, 'Mozambico'),
(154, 'Namibia'),
(155, 'Nauru'),
(156, 'Nepal'),
(157, 'Nicaragua'),
(158, 'Niger'),
(159, 'Nigeria'),
(160, 'Niue'),
(161, 'Norvegia'),
(162, 'Nuova Caledonia'),
(163, 'Nuova Zelanda'),
(164, 'Oman'),
(165, 'Paesi Bassi'),
(166, 'Pakistan'),
(167, 'Palau'),
(168, 'Palestina'),
(169, 'Panam'),
(170, 'Papua Nuova Guinea'),
(171, 'Paraguay'),
(172, 'Per'),
(173, 'Polinesia Francese'),
(174, 'Polonia'),
(175, 'Porto Rico'),
(176, 'Portogallo'),
(177, 'Monaco'),
(178, 'Qatar'),
(179, 'Regno Unito'),
(180, 'RD del Congo'),
(181, 'Rep. Ceca'),
(182, 'Rep. Centrafricana'),
(183, 'Rep. del Congo'),
(184, 'Rep. Dominicana'),
(185, 'Riunione'),
(186, 'Romania'),
(187, 'Ruanda'),
(188, 'Russia'),
(189, 'Sahara Occidentale'),
(190, 'Saint Kitts e Nevis'),
(191, 'Santa Lucia'),
(192, 'Sant''Elena, Ascensione e Tristan da Cunha'),
(193, 'Saint Vincent e Grenadine'),
(194, 'Saint-Barth'),
(195, 'Saint-Martin'),
(196, 'Saint-Pierre e Miquelon'),
(197, 'Samoa'),
(198, 'Samoa Americane'),
(199, 'San Marino'),
(201, 'Senegal'),
(202, 'Serbia'),
(203, 'Seychelles'),
(204, 'Sierra Leone'),
(205, 'Singapore'),
(206, 'Sint Maarten'),
(207, 'Siria'),
(208, 'Slovacchia'),
(209, 'Slovenia'),
(210, 'Somalia'),
(211, 'Spagna'),
(212, 'Sri Lanka'),
(213, 'Stati Uniti'),
(214, 'Sudafrica'),
(215, 'Sudan'),
(216, 'Sudan del Sud'),
(217, 'Suriname'),
(218, 'Svalbard e Jan Mayen'),
(219, 'Svezia'),
(220, 'Svizzera'),
(221, 'Swaziland'),
(222, 'Taiwan'),
(223, 'Tagikistan'),
(224, 'Tanzania'),
(225, 'Terre australi e antartiche francesi'),
(226, 'Territorio britannico dell''oceano Indiano'),
(227, 'Thailandia'),
(228, 'Timor Est'),
(229, 'Togo'),
(230, 'Tokelau'),
(231, 'Tonga'),
(232, 'Trinidad e Tobago'),
(233, 'Tunisia'),
(234, 'Turchia'),
(235, 'Turkmenistan'),
(236, 'Turks e Caicos'),
(237, 'Tuvalu'),
(238, 'Ucraina'),
(239, 'Uganda'),
(240, 'Ungheria'),
(241, 'Uruguay'),
(242, 'Uzbekistan'),
(243, 'Vanuatu'),
(244, 'Venezuela'),
(245, 'Vietnam'),
(246, 'Wallis e Futuna'),
(247, 'Yemen'),
(248, 'Zambia'),
(249, 'Zimbabwe')
END